# Using the Unsafe Foods Database

## Understanding the Database

![alt text]({{ site.url }}/assets/images/UnsafeFoodsDatabase.png "Unsafe Foods DB Schema")

The Unsafe Foods Database is a relational Postgres database that facilitates the querying and analysis of Amazon review data with respect to historical FDA recall data. We gathered the Amazon Review data from a [historical dataset](http://jmcauley.ucsd.edu/data/amazon/) that was published by Julian McAuley at UCSD. This data contains approximately 1.8 million individual reviews that include the reviewer ID, date and time of the review, the text, summary, rating, and product metadata.

## Connecting to the Database in Python

In python, you need to download a module to connect with the PostGres database. My preferred module is psycopg2. In order to install this package successfully, you must install its dependencies first using the following commands in bash:

```bash
sudo apt-get install gcc
sudo apt-get install python-setuptools
sudo easy_install psycopg2
```

After installing, you can invoke the module in your Python script and connect to the database using the following command and parameters:

```python
import psycopg2

#Connect to database
conn = psycopg2.connect(database = <Database-Name>, user = <your-user-name>, password = <your-password>, host = <your-host-name>, port = <your port number, usually 5432>)

print("Opened database successfully")
```

## Querying the Database

Using the above connection info, this section will connect to the database and execute some queries to illustrate the database's capabilities.

In [2]:
import psycopg2

#We also want to import pandas and numpy to work with the data we have fetched
import pandas as pd
import numpy as np

#Connect to database; input depends on your settings
conn = psycopg2.connect(database=<db_name>, user=<user_name>, password=<password>, host=<host_name>, port=<port_name>)

print("Opened database successfully")

Opened database successfully

First, let's go ahead and look at some of the metadata that we are working with. How many products are there per category?

In [3]:
'''
You need to set up a cursor before you start executing queries.
One way to look at it is that your connection, 'conn', is your ticket to the database,
while your cursor, cur, will be your shopping cart.
'''
cur = conn.cursor()

In [4]:
#execute SQL query
cur.execute('SELECT c.category_name, count(*) as NumProducts from\
                Category c Join CategoryAssignment ca on c.category_id = ca.category_id\
                JOIN Product p on ca.product_id = p.product_id\
                group by c.category_name order by NumProducts DESC;')

#fetch table from the cursor
category_breakdown = pd.DataFrame(cur.fetchall())

In [5]:
category_breakdown

                              0       1
0        Grocery & Gourmet Food  171760
1                     Beverages    3925
2              Cooking & Baking    2434
3                           Tea    1791
4                     Chocolate    1043
5                   Snack Foods     983
6                        Coffee     949
7             Candy & Chocolate     927
8                  Tea Samplers     763
9                        Herbal     583
10                        Sugar     489
11            Single-Serve Cups     464
12                   Baby Foods     436
13              Breakfast Foods     418
14                       Cereal     412
15                          Nut     411
16                     Vinegars     396
17                         Oils     396
18        Single Herbs & Spices     394
19                        Fruit     370
20                         Bars     343
21                 Baby Formula     324
22                       Sauces     298
23                Energy Drinks     272
24            Sugar Substitutes     254
25                       Juices     251
26                      Cereals     239
27                       Sugars     234
28                  Chewing Gum     229
29                  Fruit Juice     227
..                          ...     ...
486                      Europe       1
487                   Smoothies       1
488                Garam Masala       1
489               Wasabi Powder       1
490                     Arborio       1
491                     Jasmine       1
492                   Hazelnuts       1
493                 Bloody Mary       1
494                 Blue Cheese       1
495                     Fajitas       1
496                More Systems       1
497                      Oyster       1
498                     Fusilli       1
499                   Sage Leaf       1
500                  Dendrobium       1
501                       Bacon       1
502                   Capellini       1
503                     Germany       1
504        Stuffing Side Dishes       1
505                   Asafetida       1
506                   Bluegrass       1
507              Fresh Wreathes       1
508             Cilantro Flakes       1
509                       Grits       1
510                       Cases       1
511  Ice Cream Cones & Toppings       1
512                       Blues       1
513                        Ziti       1
514                      Bamboo       1
515               Wheat Berries       1

[516 rows x 2 columns]

What about the number of reviews per category?

In [6]:
#execute SQL query
cur.execute('SELECT c.category_name, count(*) as NumReviews from\
                Category c Join CategoryAssignment ca on c.category_id = ca.category_id\
                JOIN Review r on ca.product_id = r.product_id\
                group by c.category_name order by NumReviews DESC;')

#fetch table from the cursor
category_breakdown_reviews = pd.DataFrame(cur.fetchall())

In [7]:
category_breakdown_reviews

                              0        1
0        Grocery & Gourmet Food  1077410
1                     Beverages    23570
2              Cooking & Baking    20297
3                           Tea     9737
4                         Sugar     5793
5                      Vinegars     4792
6                          Oils     4792
7                     Chocolate     4482
8                        Coffee     4431
9             Candy & Chocolate     3981
10                   Baby Foods     3755
11                       Herbal     3609
12        Single Herbs & Spices     3582
13                 Baby Formula     3553
14                          Nut     3284
15                      Coconut     3276
16                  Snack Foods     3224
17                       Sugars     2943
18            Sugar Substitutes     2848
19                 Tea Samplers     2303
20      Meal Replacement Drinks     2244
21                       Cereal     2013
22              Breakfast Foods     2009
23            Single-Serve Cups     1854
24                        Green     1808
25                  Chewing Gum     1721
26                        Fruit     1650
27                         Bars     1630
28                         Nuts     1604
29                 Nuts & Seeds     1555
..                          ...      ...
445                  Table Salt        1
446                     Oranges        1
447           Spanish & Mexican        1
448               Wasabi Powder        1
449                 Bloody Mary        1
450                        Ziti        1
451                 Blue Cheese        1
452                        Pita        1
453             Split Pea Soups        1
454                    Saltines        1
455                    Bay Leaf        1
456                       Baked        1
457                 Adobo Sauce        1
458                Cooking Wine        1
459              Sloppy Joe Mix        1
460                      Peeled        1
461               Cashew Butter        1
462              Chrysanthemums        1
463                       Pilaf        1
464                  Enchiladas        1
465                     Brittle        1
466                      Paella        1
467                   Bluegrass        1
468  Ice Cream Cones & Toppings        1
469                    Couscous        1
470             Unroasted Beans        1
471              Party Supplies        1
472                         Egg        1
473                      Lemons        1
474                        Beef        1

[475 rows x 2 columns]

How about we start looking at recalled products? Maybe a certain category gets a lot of recalls?

In [8]:
#execute SQL query
cur.execute('SELECT c.category_name, count(*) as NumRecalls from\
                Category c Join CategoryAssignment ca on c.category_id = ca.category_id\
                JOIN recalledproduct rp on ca.product_id = rp.product_id\
                where ca.product_id in (select product_id from recalledproduct)\
                group by c.category_name order by NumRecalls DESC;')

#fetch table from the cursor
category_breakdown_recalls = pd.DataFrame(cur.fetchall())

In [9]:
category_breakdown_recalls

                                  0    1
0            Grocery & Gourmet Food  158
1                              Bars    6
2                               Nut    5
3                       Snack Foods    4
4             Single Herbs & Spices    3
5                            Butter    3
6              Energy & Nutritional    3
7                            Cereal    3
8                 Candy & Chocolate    3
9                   Breakfast Foods    3
10          Breakfast & Cereal Bars    3
11                        Chocolate    3
12                           Garlic    2
13                           Peanut    2
14                    Peanut Butter    2
15                 Cooking & Baking    2
16                      Nut Butters    2
17                Seasoned Coatings    1
18                            Cocoa    1
19                   Dips & Spreads    1
20                         Crackers    1
21                             Beef    1
22               Leaveners & Yeasts    1
23                            Stews    1
24                          Cookies    1
25                            Chili    1
26                         Allspice    1
27                        Trail Mix    1
28                        Beverages    1
29                        Hot Cocoa    1
30  Breadcrumbs & Seasoned Coatings    1
31                       Beef Soups    1
32             Canned & Jarred Food    1
33                            Ranch    1
34                      Breadcrumbs    1

All of our products are in the Grocery and Gourmet Food category, but it looks like Canned Dry & Packaged Foods might be the biggest headache for Amazon.</br>
What about brands? What is the range of number of recalls that a single brand endured within the time frame of our recall data set?

In [10]:
#execute SQL query
cur.execute('SELECT b.brand_id, count(*) as NumRecalls from\
                Brand b Join Product p on b.brand_id = p.brand_id\
                join recalledproduct rp on p.product_id = rp.product_id\
                group by b.brand_id order by NumRecalls DESC;')

#fetch table from the cursor
brand_breakdown = pd.DataFrame(cur.fetchall())

In [11]:
brand_breakdown

       0   1
0   5158  13
1   7169   8
2   2650   8
3   9864   8
4   6327   5
5   1154   5
6   8812   4
7   7259   4
8   8705   3
9   3321   3
10  4942   2
11  6382   2
12  3802   2
13  8864   2
14  6689   2
15   845   2
16  7927   2
17  7497   2
18  8337   2
19  3127   2
20   985   2
21    91   1
22  8366   1
23  8344   1
24  2683   1
25  2100   1
26  7326   1
27  6086   1
28   230   1
29  1410   1
..   ...  ..
33   122   1
34  5922   1
35  7174   1
36  6838   1
37  9259   1
38  7592   1
39  7123   1
40  9899   1
41  8245   1
42  4064   1
43  9472   1
44  3026   1
45   753   1
46  6667   1
47  7331   1
48  7770   1
49  7145   1
50  6161   1
51  1350   1
52  8329   1
53  2833   1
54  1972   1
55  9102   1
56  5410   1
57  6329   1
58   877   1
59  5781   1
60  3895   1
61  7129   1
62  4977   1

[63 rows x 2 columns]

Don't forget to close your connection!

In [12]:
conn.close()